title: ZFC
description: ZFC proofs
lang: en

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge

defaults:
  - scope:
      path: ""
    values:
      layout: default

exclude:
  - README.md
